/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package questao2;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.eclipse.persistence.jpa.jpql.parser.DateTime;

/**
 *
 * @author RenatoD
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nomeFuncionario = new javax.swing.JLabel();
        field_nomeFuncionario = new javax.swing.JTextField();
        label_dataEntrada = new javax.swing.JLabel();
        field_dataEntrada = new javax.swing.JTextField();
        label_dataNascimento = new javax.swing.JLabel();
        field_dataNascimento = new javax.swing.JTextField();
        field_salario = new javax.swing.JTextField();
        label_salario = new javax.swing.JLabel();
        button_Calcular = new javax.swing.JButton();
        label_Resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nomeFuncionario.setText("Nome Funcionário:");

        label_dataEntrada.setText("Data de Entrada:");

        label_dataNascimento.setText("Data de Nascimento:");

        label_salario.setText("Salário:");

        button_Calcular.setText("Calcular");
        button_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CalcularActionPerformed(evt);
            }
        });

        label_Resultado.setText("Gratificação:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nomeFuncionario)
                    .addComponent(field_nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dataEntrada)
                    .addComponent(field_dataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dataNascimento)
                    .addComponent(field_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_salario)
                    .addComponent(field_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Resultado)
                    .addComponent(button_Calcular))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_nomeFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_dataEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_dataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_dataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_salario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_Calcular)
                .addGap(27, 27, 27)
                .addComponent(label_Resultado)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CalcularActionPerformed
        if (validarCampos()) {
            String nome = field_nomeFuncionario.getText();
            String dataEntrada = field_dataEntrada.getText();
            String dataNascimento = field_dataNascimento.getText();
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");

            double gratificacao = 0;
            Date dataEntradaf = null;
            Date dataNascimentof = null;
            try {
                dataEntradaf = format.parse(dataEntrada);
                dataNascimentof = format.parse(dataNascimento);
            } catch (ParseException ex) {
                Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
            }
            double salario = Double.parseDouble(field_salario.getText());

            Calendar entrada = Calendar.getInstance();
            entrada.setTime(dataEntradaf);

            Calendar nascimento = Calendar.getInstance();
            nascimento.setTime(dataNascimentof);

            int anoEntrada = entrada.get(Calendar.YEAR);
            int anoNascimento = nascimento.get(Calendar.YEAR);
            int anoAtual = Calendar.getInstance().get(Calendar.YEAR);

            int diferenca = anoAtual - anoEntrada;
            int idade = anoAtual - anoNascimento;

            if (diferenca >= 10) {
                
                gratificacao = (0.15 * salario);
            } else if (diferenca >= 5 && diferenca <= 7) {

                gratificacao = 0.102 * salario;
            } else if (diferenca <= 3) {

                gratificacao = 0.102 * salario;
            }

            if (idade >= 50) {
                gratificacao = gratificacao + (0.12 * gratificacao);
            }
            
            label_Resultado.setText(String.valueOf(gratificacao));
        }
    }//GEN-LAST:event_button_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Calcular;
    private javax.swing.JTextField field_dataEntrada;
    private javax.swing.JTextField field_dataNascimento;
    private javax.swing.JTextField field_nomeFuncionario;
    private javax.swing.JTextField field_salario;
    private javax.swing.JLabel label_Resultado;
    private javax.swing.JLabel label_dataEntrada;
    private javax.swing.JLabel label_dataNascimento;
    private javax.swing.JLabel label_nomeFuncionario;
    private javax.swing.JLabel label_salario;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        if (field_nomeFuncionario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o nome do funcionário", "Mensagem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (field_dataEntrada.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a data de entrada na empresa.", "Mensagem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (field_dataNascimento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a data de nascimento do funcionário.", "Mensagem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (field_salario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o salário do funcionário.", "Mensagem", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
}
